import os

from utils.utils import get_project_root

PROJECT_PATH = get_project_root()

CHECKPOINTS_PATH = PROJECT_PATH + '/checkpoints'
if not os.path.exists(CHECKPOINTS_PATH):
    os.mkdir(CHECKPOINTS_PATH)

GENERATOR_CHECKPOINT_PATH = CHECKPOINTS_PATH + '/generator'
if not os.path.exists(GENERATOR_CHECKPOINT_PATH):
    os.mkdir(GENERATOR_CHECKPOINT_PATH)

DISCRIMINATOR_CHECKPOINT_PATH = CHECKPOINTS_PATH + '/discriminator'
if not os.path.exists(DISCRIMINATOR_CHECKPOINT_PATH):
    os.mkdir(DISCRIMINATOR_CHECKPOINT_PATH)

CURRENT_CHECKPOINT_PATH = CHECKPOINTS_PATH + '/current'
if not os.path.exists(CURRENT_CHECKPOINT_PATH):
    os.mkdir(CURRENT_CHECKPOINT_PATH)

GENERATOR_CHECKPOINT = CURRENT_CHECKPOINT_PATH + '/generator.tar'
# GENERATOR_CHECKPOINT = GENERATOR_CHECKPOINT_PATH + '/00300.tar'
DISCRIMINATOR_CHECKPOINT = CURRENT_CHECKPOINT_PATH + '/discriminator.tar'
# DISCRIMINATOR_CHECKPOINT = DISCRIMINATOR_CHECKPOINT_PATH + '/00300.tar'

RESULT_PATH = PROJECT_PATH + '/results'
if not os.path.exists(RESULT_PATH):
    os.mkdir(RESULT_PATH)

GENERATOR_RESULT_PATH = RESULT_PATH + '/generator'
if not os.path.exists(GENERATOR_RESULT_PATH):
    os.mkdir(GENERATOR_RESULT_PATH)

CURRENT_RESULT_PATH = RESULT_PATH + '/current'
if not os.path.exists(CURRENT_RESULT_PATH):
    os.mkdir(CURRENT_RESULT_PATH)

GENERATOR_BATCH_SIZE = 64
VALIDATION_BATCH_SIZE = 32
